spring.application.name=user-management

spring.main.banner-mode=off

server.port=8082

spring.datasource.url=jdbc:h2:./h2-database/prototypeDB;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=